### ISSUE TITLE
What license are these samples?

### ISSUE THREAD

**Issue by fire** [AssemblyScript/examples#13]
License?

**Comment by dcodeIO** [comment]
Oh, we forgot to add a license file here. Would Apache-2.0 work for you, just like the compiler, or would you prefer something like MIT?

**Comment by fire** [comment]
I would like to not have to add a license, but that's not possible.

Adding Apache-2.0 would make your project require only one license txt.

Adding both Apache-2.0 and MIT would require adding texts of both to satisfy the agreement of using type script? I'm not sure.

I want something that is easy to comply with.

**Comment by fire** [comment]
@dcodeIO ping

**Comment by dcodeIO** [comment]
Added a LICENSE file to the top-level that covers all examples

**Comment by fire** [comment]
Thanks
