### ISSUE TITLE
Trying to run the examples gives error: "LinkError: WebAssembly.instantiate(): Import #0 module="env" function="Math.log""

### ISSUE THREAD

**Issue by Sakari369** [AssemblyScript/examples#17]
Trying to build and load the examples with a recent version of Chrome and Safari on macOS Monterey arm64 gives the following error in console.log:

LinkError: WebAssembly.instantiate(): Import #0 module="env" function="Math.log" error: function import requires a callable

**Comment by dcodeIO** [comment]
Seems the examples are not yet updated to v0.20 of the compiler but still require v0.19. Makes sense to update them :)

**Comment by Sakari369** [comment]
Well, it definitely makes as one cannot run the examples right now without having to figure out how they should work .. :) :P

**Comment by jxlust** [comment]
I use in v0.20, but I don't know how to set it globally
```js  
env: {
       'Math.random': Math.random
      }
```

**Comment by MaxGraey** [comment]
Should be fixed now
